apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
spec:
  template:
    spec:
      containers:
        - name: mysql
          resources:
            #$patch: delete      
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "300m"
