apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  ports:
    - targetPort : 80
      port: 80
      nodePort: 30006
  selector:
    app: nginx
  type: NodePort

